### ISSUE TITLE
aar 404 

### ISSUE THREAD

**Issue by RanyAlbegWein** [mobileprint/android-print-sdk#13]
Hello,
I'm unable to reach the `aar` file. Is there any alternative source?

Thank you!

**Comment by cie6868** [comment]
In case anyone else comes across this, it looks like you need to compile it yourself.

Download the source from https://github.com/mobileprint/android-print-sdk/archive/master.zip and open and build in Android Studio.

Then use the fresh aar file and follow the instructions in https://github.com/mobileprint/android-print-sdk/wiki/Install-With-.aar-File . Remember to rename `hpprint` to `mobileprintsdk`.

Also the line `flatDir { dirs 'libs' }` goes in the `allprojects` configuration in the project `build.gradle` file. The `compile(...)` line goes in your app's `build.gradle`.

If you're using gradle plugin 3.0.0 or higher, you might have to add `android.enableAapt2=false` to your `grade.properties` file or your app build will fail.
