### ISSUE TITLE
Unknown host 'd29vzk4ow07wi7.cloudfront.net'. You may need to adjust the proxy settings in Gradle.

### ISSUE THREAD

**Issue by GzxdH** [mobileprint/android-print-sdk#28]
https://github.com/mobileprint/android-print-sdk/archive/master.zip 

但是我的AndroidStudio没有编译成功，我接下来该怎么做呢
But my AndroidStudio did not compile successfully. What should I do next

如果发现这个issues 请您回复我，谢谢
If you find this issue, please reply to me, thank you

**Comment by SaturnoMichael** [comment]
me too, tengo el mismo problema
